registries:
  npm-github:
    replaces-base: true
    token: ${{ secrets.MY_GITHUB_PERSONAL_TOKEN }}
    type: npm-registry
    url: https://npm.pkg.github.com
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
      time: '05:00'
  - directory: /
    package-ecosystem: npm
    registries:
      - npm-github
    schedule:
      interval: daily
      time: '05:00'
version: 2
