version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.MY_GITHUB_PERSONAL_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '05:00'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '05:00'
    registries:
      - npm-github
