sonar.projectKey=OlivierZal_com.heatzy
sonar.organization=olivierzal
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=**/*.jpg,**/*.png,coverage/**,settings/index.mjs
sonar.coverage.exclusions=tests/**,**/*.config.*,settings/**,scripts/**
sonar.cpd.exclusions=**/*.config.*,settings/index.html
