name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: npm scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x', '16.x', '22.x']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Bump version
        run: |
          APP_VERSION=$(jq -r .version .homeycompose/app.json)
          jq ".version=\"$APP_VERSION\"" package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Update package-lock.json
        run: npm install
      - name: Lint and fix errors
        run: npm run lint:fix
      - name: Format code
        run: npm run format:fix
      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add -A
          if ! git diff --cached --exit-code; then
            git commit -m "Code maintenance: bump version, lint and format"
            if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
              echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
              BRANCH_NAME="maintenance-$(date +'%Y%m%d%H%M%S')"
              git checkout -b "$BRANCH_NAME"
              git push origin "$BRANCH_NAME"
              gh pr create --base main --head "$BRANCH_NAME" --title "Maintenance PR" --body "Automatic code maintenance: bump version, lint and format."
              gh pr merge --auto --squash --delete-branch ${{ github.event.pull_request.html_url }}
            else
              git pull origin ${{ github.head_ref }} --rebase
              git push origin HEAD:${{ github.head_ref }}
            fi
          else
            echo "No changes to commit."
          fi
